Hw02 unpack string is completed
Remneva/otus_hw pull request #1
Opened 2020-09-13 12:49 UTC by Remneva

2020-09-16 09:40 UTC, Antonboom requested changes
https://otus.ru/teacher-lk/homework/71747/8085/

Здравствуйте!
Хорошая работа.

1) Чтобы шаблон нашелся, внимательнее проверьте его название в URL (оканчиваться должен на `.md`):
https://github.com/Remneva/otus_hw/tree/master/.github/PULL_REQUEST_TEMPLATE

2) Жду тесты и более эффективную сборку строки

Спасибо!
5 / 10

2020-09-16 09:40 UTC, Antonboom commented on hw02_unpack_string/unpack.go
> +func Unpack(s string) (string, error) {
Не вижу новых тестов :)

2020-09-16 09:40 UTC, Antonboom commented on hw02_unpack_string/unpack.go
> +	var result string
как насчет `strings.Builder`?

2020-09-16 09:40 UTC, Antonboom commented on hw02_unpack_string/unpack.go
> +	_, err := strconv.Atoi(string([]rune(s)[i-1])) // проверка предыдущего символа - не должно быть два инта подряд
для чего повсеместный каст к `[]rune`?

индексация от s[i] не подойдет?

2020-09-16 09:40 UTC, Antonboom commented on hw02_unpack_string/unpack.go
> +	if b == 0 { // если инт = 0, не повторять букву ни одного раза
Repeat(..., 0) не работает? :)

2020-09-16 11:43 UTC, Remneva commented on hw02_unpack_string/unpack.go
> +	if b == 0 { // если инт = 0, не повторять букву ни одного раза
в моей реализации получается, что на момент проверки значения инта, та буква, которая шла перед ним, уже добавлена к `result string` один раз. Если выполнить Repeat 0 раз, то в моем случае будет "а0" = "а", но не "а0" = "". Правильнее ли будет добавлять символ к `result string` только после проверки следующего символа?

2020-09-17 14:19 UTC, Antonboom commented on hw02_unpack_string/unpack.go
> +	if b == 0 { // если инт = 0, не повторять букву ни одного раза
нет, ваш вариант приемлем

2020-09-20 15:15 UTC, Remneva commented on hw02_unpack_string/unpack.go
> +func Unpack(s string) (string, error) {
Тесты добавлены

2020-09-20 15:16 UTC, Remneva commented on hw02_unpack_string/unpack.go
> +	var result string
функция переписана с применением strings.Builder

2020-09-20 15:24 UTC, Remneva commented on hw02_unpack_string/unpack.go
> +	_, err := strconv.Atoi(string([]rune(s)[i-1])) // проверка предыдущего символа - не должно быть два инта подряд
индексация подошла, спасибо)

2020-09-21 05:13 UTC, Antonboom commented on hw02_unpack_string/unpack_test.go
> +			expected: "ᛯáá",
а почему здесь не 
```
ᛯᛯᛯ
```
?

2020-09-23 15:50 UTC, Remneva commented on hw02_unpack_string/unpack_test.go
> +			expected: "ᛯáá",
Не сразу дошло, что обращалась к байту, потому что со строкой, состоящей из символов размером в 1 байт это работало, а с символами из 2 байт, всё поехало. Вот теперь пофиксила.

2020-09-24 05:28 UTC, Antonboom commented on hw02_unpack_string/unpack_test.go
> +			expected: "ᛯáá",
вот вам и TDD, вы, видимо тест написали, опираясь на результаты программы
а надо бы наоборот :)

2020-09-24 05:29 UTC, Antonboom approved these changes
Принято
10 / 10

2020-09-24 05:29 UTC, Antonboom commented on hw02_unpack_string/unpack.go
> +		result.WriteString(string(str[:size-1]))
WriteByte / WriteRune?

2020-11-08 17:43 UTC, merged