Hw 13
Remneva/otus_hw pull request #12
Opened 2020-12-29 07:20 UTC by Remneva

### Критерии оценки

- [ ] - Makefile заполнен и пайплайн зеленый - 1 балл
- [ ] - Реализовано GRPC API и `make generate` - 3 балла
- [ ] - Реализовано HTTP API - 2 балла
- [ ] - Написаны юнит-тесты на API - до 2 баллов
- [ ] - Понятность и чистота кода - до 2 баллов

2020-12-30 04:52 UTC, balabanovds requested changes
Спасибо за работу.

На данный момент очень много замечаний.
Уникальные указал в ревью. Аналогичные по коду опустил.

Прокомментируйте пожалуйста.

Будут вопросы - доступен в Slack

Успехов!

https://otus.ru/teacher-lk/homework/71747/8093/

2020-12-30 04:52 UTC, balabanovds commented on hw07_file_copying/out.txt
> +nder Windows.
Этот файл как сюда попал?

2020-12-30 04:52 UTC, balabanovds commented on hw12_13_14_15_calendar/README.md
> +- [Домашнее задание №12 «Заготовка сервиса Календарь»](docs2_README.md)
битые ссылки

2020-12-30 04:52 UTC, balabanovds commented on hw12_13_14_15_calendar/api/EventService.proto
> +message Date {
есть причина указывать Date? Он где-то используется?

2020-12-30 04:52 UTC, balabanovds commented on hw12_13_14_15_calendar/Makefile
> +	$(BIN) -config ./configs/config.toml
run падает с ошибкой - не может найти конфиг
Зачем Вы его перенесли в ./cmd/calendar?

2020-12-30 04:52 UTC, balabanovds commented on hw12_13_14_15_calendar/cmd/calendar/main.go
> +var grpc *internalgrpc.Server
зачем эти две переменные выносить в глобальную область видимости пакета?
это не нужно

2020-12-30 04:52 UTC, balabanovds commented on hw12_13_14_15_calendar/cmd/calendar/main.go
> +	storage := new(sql.Storage)
у Вас есть конструктор для инициализации
а если я захочу in-memory DB, зачем мне тогда SQL?

2020-12-30 04:52 UTC, balabanovds commented on hw12_13_14_15_calendar/cmd/calendar/main.go
> +		_, mux := internalhttp.NewHandler(ctx, application)
зачем в main горутине знать о внутренней реализации сервера?
достаточно заинжектить application в конструктор сервера.

2020-12-30 04:52 UTC, balabanovds commented on hw12_13_14_15_calendar/cmd/calendar/main.go
> +			application.Log.Fatal("failed to start http server: " + err.Error())
почему здесб обращаетесь к application, а не к logg?

2020-12-30 04:52 UTC, balabanovds commented on hw12_13_14_15_calendar/cmd/calendar/main.go
> +		wg.Done()
defer

2020-12-30 04:52 UTC, balabanovds commented on hw12_13_14_15_calendar/cmd/calendar/main.go
> +		wg.Done()
defer

2020-12-30 04:52 UTC, balabanovds commented on hw12_13_14_15_calendar/cmd/calendar/main.go
> +	go signalChan(application, http, grpc)
Вы дождались выполнения горутин http и grpc, затем создали новую горутину по обработке сигналов от ОС. 
Вы уверены, что эта горутина завершится раньше чем основная горутина?

2020-12-30 04:52 UTC, balabanovds commented on hw12_13_14_15_calendar/configs/config.go
> +	fmt.Println("DSN: ", c.PSQL.DSN)
зачем выводите в stdout все переменные? там может быть чувствительная информация

2020-12-30 04:52 UTC, balabanovds commented on hw12_13_14_15_calendar/internal/app/app.go
> +	if !c.Mode.MemMode {
эта логика должна быть в main. в main на основании конфига мы должны выбирать какой стор использовать

2020-12-30 04:52 UTC, balabanovds commented on hw12_13_14_15_calendar/internal/logger/logger.go
> +	cfg := zap.NewProductionConfig()
а если я хочу сделать разное логирование для прода и для дева?

2020-12-30 04:52 UTC, balabanovds commented on hw12_13_14_15_calendar/internal/logger/logger.go
> +		return nil, errors.Wrap(err, "Logger build failed")
так как go1.15 то можно использовать встроенный враппер fmt.Errorf("some text: %w", err)

2020-12-30 04:52 UTC, balabanovds commented on hw12_13_14_15_calendar/internal/logger/logger.go
> +func Exists(name string) bool {
зачем экспортируете?

2020-12-30 04:52 UTC, balabanovds commented on hw12_13_14_15_calendar/internal/server/grpc/server.go
> +func (s *Server) Start(ctx context.Context) error {
данный метод должен запускать сервер, а сейчас он просто виснет на контексте
конструктор выше NewServer должен только создавать новый инстанс, а он виснет на server.Serve

2020-12-30 04:52 UTC, balabanovds commented on hw12_13_14_15_calendar/internal/server/grpc/server.go
> +	ctx.Done()
ctx.Done() возвращает канал, который мы должны слушать.
если Вы хотите завершить контекст, то нужно вызывать cancel-функцию (если это конечно context.WithCancel), но здесь это не нужно

2020-12-30 04:52 UTC, balabanovds commented on hw12_13_14_15_calendar/internal/server/grpc/server.go
> +	s.app.Log.Info("Get Event grpc method", zap.Int("req", int(req.Id)))
логирование на каждом уровне должно быть отдельно.

2020-12-30 04:52 UTC, balabanovds commented on hw12_13_14_15_calendar/internal/server/grpc/server.go
> +		eve, err = s.app.Repo.GetEvent(ctx, req.Id)
на данном уровне не должно быть обращения к уровню БД

2020-12-30 04:52 UTC, balabanovds commented on hw12_13_14_15_calendar/internal/server/grpc/server.go
> +	StartTime, err := ptypes.TimestampProto(eve.StartTime)
экспортируемая переменная?

2020-12-30 04:52 UTC, balabanovds commented on hw12_13_14_15_calendar/internal/server/grpc/server.go
> +	eve.ID = req.Id
дублирование кода, можно вынести в утильную функцию

2020-12-30 04:52 UTC, balabanovds commented on hw12_13_14_15_calendar/internal/server/grpc/server_test.go
> +type StoreSuite struct {
объявление структуры должно быть перед его методами

2020-12-30 04:52 UTC, balabanovds commented on hw12_13_14_15_calendar/internal/server/http/middleware.go
> +func requestLoggerMiddleware(m *MyHandler, h http.HandlerFunc) http.HandlerFunc {
может лучше сделать его методом MyHandler? Вы оттуда по сути используете только логгер

2020-12-30 04:52 UTC, balabanovds commented on hw12_13_14_15_calendar/internal/server/http/server.go
>  type Application interface {
зачем оставили пустой интерфейс?

2020-12-30 04:52 UTC, balabanovds commented on hw12_13_14_15_calendar/internal/server/http/server.go
> +	err := server.ListenAndServe()
опять Вы запускаете сервер в конструкторе

2020-12-30 04:52 UTC, balabanovds commented on hw12_13_14_15_calendar/internal/server/http/server.go
> +	select { //nolint
ListenAndServe должен быть тут. контекст тут не нужен

2020-12-30 04:52 UTC, balabanovds commented on hw12_13_14_15_calendar/internal/server/http/server.go
> +	ctx.Done()
опять пытаетесь так закрыть контекст?

2020-12-30 04:52 UTC, balabanovds commented on hw12_13_14_15_calendar/internal/server/http/server.go
> +		m.app.Log.Info("BadRequest", zap.String("ReadAll", err.Error()))
опять логирование не из того слоя

2020-12-30 04:52 UTC, balabanovds commented on hw12_13_14_15_calendar/internal/server/http/server.go
> +		id, err = m.app.Repo.AddEvent(m.ctx, eve)
опять обращение к слою БД

2020-12-30 04:52 UTC, balabanovds commented on hw12_13_14_15_calendar/internal/server/http/server.go
> +	resp.Header().Set("Content-Type", "application/json; charset=utf-8")
в каждом хендлере Вы задаете одинаковые заголовки, это повод создать еще один middleware

2020-12-30 04:52 UTC, balabanovds commented on hw12_13_14_15_calendar/internal/server/http/server.go
> +	m.app.Log.Info("Update grpc method", zap.Int("req", int(rb.ID)))
grpc?

2020-12-30 04:52 UTC, balabanovds commented on hw12_13_14_15_calendar/internal/server/http/server_test.go
> +type StoreSuite struct {
опять объявление структуры в конце

2020-12-30 04:52 UTC, balabanovds commented on hw12_13_14_15_calendar/internal/storage/memory/event.go
> +type EventMap struct {
не конкурентное обращение к мапе

2020-12-30 04:52 UTC, balabanovds commented on hw12_13_14_15_calendar/internal/storage/sql/storage.go
> +func New(s storage.EventsStorage) *Storage {
конструктор нигде не вызывается

2020-12-30 04:52 UTC, balabanovds commented on hw12_13_14_15_calendar/internal/storage/sql/storage.go
>  func (s *Storage) Close(ctx context.Context) error {
ctx нигде не используется

2020-12-30 04:52 UTC, balabanovds commented on hw12_13_14_15_calendar/internal/storage/sql/storage.go
> +		return errors.Wrapf(ErrSQLQuery, err.Error())
fmt.Errorf

2020-12-30 04:52 UTC, balabanovds commented on hw12_13_14_15_calendar/internal/storage/sql/storage.go
> +	if err != nil {
а как мы поймем что произошла ошибка именно из-за того что такой эвент уже существует?

2020-12-30 04:52 UTC, balabanovds commented on hw12_13_14_15_calendar/internal/storage/sql/storage.go
> +	if err != nil {
а если такого эвента не существует в БД?

2020-12-30 04:52 UTC, balabanovds commented on hw12_13_14_15_calendar/internal/storage/storage.go
> +	_ "github.com/jackc/pgx/v4/stdlib"
может лучше затаскивать драйвер там где он используется?

2020-12-30 04:52 UTC, balabanovds commented on hw12_13_14_15_calendar/tests/http_test.go
> +//import (
зачем такой файл на ревью?

2021-01-15 08:39 UTC, Remneva commented on hw12_13_14_15_calendar/api/EventService.proto
> +message Date {
теперь не используется, убрала

2021-01-15 08:39 UTC, Remneva commented on hw12_13_14_15_calendar/Makefile
> +	$(BIN) -config ./configs/config.toml
вернула на место

2021-01-15 08:42 UTC, Remneva commented on hw12_13_14_15_calendar/cmd/calendar/main.go
> +var grpc *internalgrpc.Server
+

2021-01-15 08:44 UTC, Remneva commented on hw12_13_14_15_calendar/cmd/calendar/main.go
> +	storage := new(sql.Storage)
теперь DB  инициализируется только когда нужно

2021-01-15 08:44 UTC, Remneva commented on hw12_13_14_15_calendar/cmd/calendar/main.go
> +			application.Log.Fatal("failed to start http server: " + err.Error())
done

2021-01-15 08:45 UTC, Remneva commented on hw12_13_14_15_calendar/cmd/calendar/main.go
> +		wg.Done()
done

2021-01-15 08:45 UTC, Remneva commented on hw12_13_14_15_calendar/cmd/calendar/main.go
> +		wg.Done()
done

2021-01-15 08:46 UTC, Remneva commented on hw12_13_14_15_calendar/cmd/calendar/main.go
> +	go signalChan(application, http, grpc)
теперь обработка сигналов запускается при старте приложения

2021-01-15 08:46 UTC, Remneva commented on hw12_13_14_15_calendar/configs/config.go
> +	fmt.Println("DSN: ", c.PSQL.DSN)
добавляла для тестирования, убрала

2021-01-15 08:46 UTC, Remneva commented on hw12_13_14_15_calendar/internal/app/app.go
> +	if !c.Mode.MemMode {
вынесено в main

2021-01-15 08:47 UTC, Remneva commented on hw12_13_14_15_calendar/internal/logger/logger.go
> +func Exists(name string) bool {
done

2021-01-15 08:47 UTC, Remneva commented on hw12_13_14_15_calendar/internal/server/grpc/server.go
> +func (s *Server) Start(ctx context.Context) error {
done

2021-01-15 08:47 UTC, Remneva commented on hw12_13_14_15_calendar/internal/server/grpc/server.go
> +	ctx.Done()
done

2021-01-15 08:47 UTC, Remneva commented on hw12_13_14_15_calendar/internal/server/grpc/server.go
> +	s.app.Log.Info("Get Event grpc method", zap.Int("req", int(req.Id)))
done

2021-01-15 08:47 UTC, Remneva commented on hw12_13_14_15_calendar/internal/server/grpc/server.go
> +		eve, err = s.app.Repo.GetEvent(ctx, req.Id)
done

2021-01-15 08:48 UTC, Remneva commented on hw12_13_14_15_calendar/internal/server/grpc/server.go
> +	StartTime, err := ptypes.TimestampProto(eve.StartTime)
done

2021-01-15 08:48 UTC, Remneva commented on hw12_13_14_15_calendar/internal/server/grpc/server.go
> +	eve.ID = req.Id
done

2021-01-15 08:48 UTC, Remneva commented on hw12_13_14_15_calendar/internal/server/grpc/server_test.go
> +type StoreSuite struct {
done

2021-01-15 08:49 UTC, Remneva commented on hw12_13_14_15_calendar/internal/server/http/server.go
> +	err := server.ListenAndServe()
done

2021-01-15 08:49 UTC, Remneva commented on hw12_13_14_15_calendar/internal/server/http/server.go
> +	select { //nolint
done

2021-01-15 08:49 UTC, Remneva commented on hw12_13_14_15_calendar/internal/server/http/server.go
> +	ctx.Done()
done

2021-01-15 08:49 UTC, Remneva commented on hw12_13_14_15_calendar/internal/server/http/server.go
> +		m.app.Log.Info("BadRequest", zap.String("ReadAll", err.Error()))
done

2021-01-15 08:49 UTC, Remneva commented on hw12_13_14_15_calendar/internal/server/http/server.go
> +		id, err = m.app.Repo.AddEvent(m.ctx, eve)
done

2021-01-15 08:50 UTC, Remneva commented on hw12_13_14_15_calendar/internal/server/http/server.go
> +	resp.Header().Set("Content-Type", "application/json; charset=utf-8")
done

2021-01-15 08:50 UTC, Remneva commented on hw12_13_14_15_calendar/internal/server/http/server_test.go
> +type StoreSuite struct {
done

2021-01-15 09:03 UTC, Remneva commented on hw12_13_14_15_calendar/internal/server/http/server.go
>  type Application interface {
done

2021-01-15 09:03 UTC, Remneva commented on hw12_13_14_15_calendar/internal/storage/sql/storage.go
> +func New(s storage.EventsStorage) *Storage {
done

2021-01-15 09:12 UTC, Remneva commented on hw12_13_14_15_calendar/internal/storage/sql/storage.go
>  func (s *Storage) Close(ctx context.Context) error {
done

2021-01-15 09:33 UTC, Remneva commented on hw12_13_14_15_calendar/internal/storage/sql/storage.go
> +		return errors.Wrapf(ErrSQLQuery, err.Error())
done

2021-01-15 10:17 UTC, Remneva commented on hw12_13_14_15_calendar/internal/storage/storage.go
> +	_ "github.com/jackc/pgx/v4/stdlib"
done

2021-01-15 11:33 UTC, Remneva commented on hw12_13_14_15_calendar/tests/http_test.go
> +//import (
done

2021-01-15 11:56 UTC, Remneva commented on hw12_13_14_15_calendar/internal/storage/sql/storage.go
> +	if err != nil {
Добавила проверку

2021-01-15 12:16 UTC, Remneva commented on hw12_13_14_15_calendar/internal/storage/sql/storage.go
> +	if err != nil {
в моей реализаии уникальный id инкрементится автоматически, поэтому такой ошибки нет

2021-01-15 12:18 UTC, Remneva commented on hw12_13_14_15_calendar/internal/server/http/server.go
> +	m.app.Log.Info("Update grpc method", zap.Int("req", int(rb.ID)))
done

2021-01-15 13:19 UTC, Remneva commented on hw07_file_copying/out.txt
> +nder Windows.
+

2021-01-15 13:19 UTC, Remneva commented on hw12_13_14_15_calendar/README.md
> +- [Домашнее задание №12 «Заготовка сервиса Календарь»](docs2_README.md)
done

2021-01-15 13:46 UTC, Remneva commented on hw12_13_14_15_calendar/cmd/calendar/main.go
> +		_, mux := internalhttp.NewHandler(ctx, application)
done

2021-01-15 13:55 UTC, Remneva commented on hw12_13_14_15_calendar/internal/logger/logger.go
> +		return nil, errors.Wrap(err, "Logger build failed")
done

2021-01-15 14:14 UTC, Remneva commented on hw12_13_14_15_calendar/internal/server/http/middleware.go
> +func requestLoggerMiddleware(m *MyHandler, h http.HandlerFunc) http.HandlerFunc {
done

2021-01-15 14:16 UTC, Remneva commented on hw12_13_14_15_calendar/internal/logger/logger.go
> +	cfg := zap.NewProductionConfig()
вот здесь не очень понятно, окружение узнавать из конфига или переменной окружения тогда?

2021-01-15 14:32 UTC, Remneva commented on hw12_13_14_15_calendar/internal/storage/memory/event.go
> +type EventMap struct {
вот тут непонятно, на каком уровне должна быть реализована конкурентность, функции работы непосредственно с мапой должны запускаться в горутинах?

2021-01-19 07:11 UTC, balabanovds requested changes
Спасибо за работу.

Есть много замечаний, в том числе архитектурных.
- посмотрите как сделать слои менее связанными (DI)
- старайтесь больше использовать интерфейсы
- не нужно использовать например логгер из слоя app в остальных слоях. сделайте app.Log -> app.log, в каждый инстанс прокидывайте свой указатель на логгер
- используйте конструкторы, и передавайте все параметры через них.
- название функции должно описывать ее суть, не стесняйтесь давать длинные имена функциям, переменным (самодокументируемый код)
- не стесняйтесь писать комментарии, там где это необходимо, без капитанства
- не надо лишний раз экспортировать функции, методы

Если будут вопросы - пишите с Слаке, попробуем разобраться

Успехов!

2021-01-19 07:11 UTC, balabanovds commented on hw12_13_14_15_calendar/cmd/calendar/main.go
> +		application = app.NewStoreApp(logg, storage, config)
Сейчас NewStoreApp принимает интерфейс `storage.EventsStorage`, а если появится новая сущность, например Users, и будет интерфейс `storage.UserStorage`, будем все переписывать? :)

2021-01-19 07:11 UTC, balabanovds commented on hw12_13_14_15_calendar/cmd/calendar/main.go
> +		application = app.NewMemApp(logg, config)
Слои app  и storage жестко связаны, а если в будущем появится еще какая-то реализация storage? 
На 49 строчке Вы уже используете DI (dependency injection), правда там нужно подумать с интерфейсом.
Почему бы для app не создать общий конструктор который принимает интерфейс?

Тогда можно будет избежать нелепых конструкций типа
```go
	if !m.app.Mode {
		id, err = m.app.Create(m.ctx, eve)
	} else {
		id, err = m.app.CreateInMemory(m.ctx, eve)
	}
```

2021-01-19 07:11 UTC, balabanovds commented on hw12_13_14_15_calendar/cmd/calendar/main.go
>  func signalChan(app *app.App, http *internalhttp.Server, grpc *internalgrpc.Server) {
Мало ли потом появится сервисов, которые надо аккуратно остановить?!

Может попробовать так: `func signalChan(app *app.App, srv ...server.Stopper)`
где
```go
type Stopper interface {
  Stop(context.Context) error
}
```

2021-01-19 07:11 UTC, balabanovds commented on hw12_13_14_15_calendar/cmd/calendar/main.go
>  func signalChan(app *app.App, http *internalhttp.Server, grpc *internalgrpc.Server) {
не нужно использовать логгер из другого слоя, мало ли какая там реализация?!
прокидывайте просто логгер если нужно

2021-01-19 07:11 UTC, balabanovds commented on hw12_13_14_15_calendar/internal/app/app.go
> +func (a *App) CreateInMemory(ctx context.Context, eve storage.Event) (int64, error) {
если использовать интерфейс, как я описал выше, то отдельная реализация для mem не нужна

2021-01-19 07:11 UTC, balabanovds commented on hw12_13_14_15_calendar/internal/server/grpc/server.go
>  	app.Log.Info("grpc is running...")
Вы опять смешиваете слои. зачем используете логер из слоя app?

2021-01-19 07:11 UTC, balabanovds commented on hw12_13_14_15_calendar/internal/server/grpc/server.go
> +func set(req *pb.Event) storage.Event {
из названия функции неясно что она делает

2021-01-19 07:11 UTC, balabanovds commented on hw12_13_14_15_calendar/internal/server/grpc/server.go
>  	if !s.app.Mode {
опять же от этих конструкций нужно избавляться..

2021-01-19 07:11 UTC, balabanovds commented on hw12_13_14_15_calendar/internal/server/http/middleware.go
> +	"test":         "test",
?

2021-01-19 07:11 UTC, balabanovds commented on hw12_13_14_15_calendar/internal/server/http/server.go
>  func NewHandler(ctx context.Context, app *app.App) (*MyHandler, *http.ServeMux) {
внутренняя функция

2021-01-19 07:11 UTC, balabanovds commented on hw12_13_14_15_calendar/internal/server/http/server.go
>  func NewServer(mux *http.ServeMux, port string, log *zap.Logger) (*Server, error) { //nolint
внутренняя функция

2021-01-19 07:11 UTC, balabanovds commented on hw12_13_14_15_calendar/internal/server/http/server.go
> +		return fmt.Errorf("creating a new ServerTransport failed: %w", err)
если не нужно оборачивать, можно вернуть сразу s.server.ListenAndServe()

2021-01-19 07:11 UTC, balabanovds commented on hw12_13_14_15_calendar/internal/server/http/server.go
> +		return fmt.Errorf("shutdown error: %w", err)
тоже можно сразу вернуть

2021-01-19 07:11 UTC, balabanovds commented on hw12_13_14_15_calendar/internal/server/http/server.go
> +	mux.HandleFunc("/set", handler.requestLoggerMiddleware(headerSetter(handler.SetEvent)))
а почуме у Вас хендлеры экспортируемые?

2021-01-19 07:11 UTC, balabanovds commented on hw12_13_14_15_calendar/internal/server/http/server.go
>  		m.app.Log.Error("Unmarshal error", zap.Error(err))
то есть если не удалось размаршаллить, то продолжаем работу? аналогичный вопрос по строке 76 (не могу там поставить комментарии)

2021-01-19 07:11 UTC, balabanovds commented on hw12_13_14_15_calendar/internal/server/http/server.go
>  		resp.WriteHeader(http.StatusBadRequest)
а ошибку в ответ записать? или ограничимся только кодом?

2021-01-19 07:11 UTC, balabanovds commented on hw12_13_14_15_calendar/internal/storage/memory/event.go
> +type EventMap struct {
у Вас скорее всего будет одновременно несколько подключений по API - вот и конкурентный доступ

2021-01-19 07:11 UTC, balabanovds commented on hw12_13_14_15_calendar/internal/storage/memory/event.go
> +	e.mu.Unlock()
закрывая мьтекс здесь Вы оставляете небезопасным доступ к мапе

также защищать нужно везде где есть доступ к мапе

2021-01-19 07:11 UTC, balabanovds commented on hw12_13_14_15_calendar/internal/storage/sql/storage.go
> -func New(s storage.EventsStorage) *Storage {
Обычно, имея конструктор, создается инстанс, и тут же передаются все зависимости, типа логгера, конфига, или если надо интерфейсы..

Вы же передаете параметры инстанса в методе Connect, что выглядит очень странно...

2021-01-19 07:11 UTC, balabanovds commented on hw12_13_14_15_calendar/internal/storage/sql/storage.go
> +		s.l.Info("Event does not exist", zap.Int64("id", ev.ID))
так может вернуть ошибку если пытались апдейтить несуществующий эвент

2021-01-19 07:11 UTC, balabanovds commented on hw12_13_14_15_calendar/internal/storage/sql/storage.go
> +		return ev, fmt.Errorf("open connection error %w", err)
то есть если эвент не найден в БД то все равно возвращаем `open connection error`?

и разве здесь проблема открытия соединения?

2021-01-19 07:11 UTC, balabanovds commented on hw12_13_14_15_calendar/internal/storage/sql/storage.go
> +	if err != nil {
то есть у Вас эвенты для одного пользователя могут накладываться и может существовать в БД два абсолютно одинаковых эвента?

2021-01-19 11:23 UTC, Remneva commented on hw12_13_14_15_calendar/cmd/calendar/main.go
> +		application = app.NewMemApp(logg, config)
теперь в App лежит интерфейс и режим работы проверяется один раз при создании App

2021-01-19 11:24 UTC, Remneva commented on hw12_13_14_15_calendar/cmd/calendar/main.go
>  func signalChan(app *app.App, http *internalhttp.Server, grpc *internalgrpc.Server) {
спасибо, так намного красивee, done

2021-01-19 11:25 UTC, Remneva commented on hw12_13_14_15_calendar/cmd/calendar/main.go
>  func signalChan(app *app.App, http *internalhttp.Server, grpc *internalgrpc.Server) {
done

2021-01-19 11:25 UTC, Remneva commented on hw12_13_14_15_calendar/internal/app/app.go
> +func (a *App) CreateInMemory(ctx context.Context, eve storage.Event) (int64, error) {
done, больше нет отдельной реализации

2021-01-19 11:25 UTC, Remneva commented on hw12_13_14_15_calendar/internal/server/grpc/server.go
>  	app.Log.Info("grpc is running...")
done

2021-01-19 11:33 UTC, Remneva commented on hw12_13_14_15_calendar/internal/server/grpc/server.go
> +func set(req *pb.Event) storage.Event {
done

2021-01-19 11:33 UTC, Remneva commented on hw12_13_14_15_calendar/internal/server/grpc/server.go
>  	if !s.app.Mode {
done

2021-01-19 11:35 UTC, Remneva commented on hw12_13_14_15_calendar/internal/server/http/server.go
>  func NewHandler(ctx context.Context, app *app.App) (*MyHandler, *http.ServeMux) {
done

2021-01-19 11:35 UTC, Remneva commented on hw12_13_14_15_calendar/internal/server/http/server.go
>  func NewServer(mux *http.ServeMux, port string, log *zap.Logger) (*Server, error) { //nolint
done

2021-01-19 11:36 UTC, Remneva commented on hw12_13_14_15_calendar/internal/server/http/server.go
> +	mux.HandleFunc("/set", handler.requestLoggerMiddleware(headerSetter(handler.SetEvent)))
done

2021-01-19 12:02 UTC, Remneva commented on hw12_13_14_15_calendar/internal/server/http/server.go
>  		m.app.Log.Error("Unmarshal error", zap.Error(err))
done

2021-01-19 12:03 UTC, Remneva commented on hw12_13_14_15_calendar/internal/server/http/server.go
>  		resp.WriteHeader(http.StatusBadRequest)
done

2021-01-19 12:07 UTC, Remneva commented on hw12_13_14_15_calendar/internal/storage/memory/event.go
> +	e.mu.Unlock()
теперь закрываю все мьютексы в дефёре

2021-01-19 12:27 UTC, Remneva commented on hw12_13_14_15_calendar/internal/storage/sql/storage.go
> +		s.l.Info("Event does not exist", zap.Int64("id", ev.ID))
done

2021-01-19 12:27 UTC, Remneva commented on hw12_13_14_15_calendar/internal/storage/sql/storage.go
> -func New(s storage.EventsStorage) *Storage {
done

2021-01-19 13:20 UTC, Remneva commented on hw12_13_14_15_calendar/internal/storage/sql/storage.go
> +	if err != nil {
теперь не накладываются

2021-01-19 13:23 UTC, Remneva commented on hw12_13_14_15_calendar/internal/storage/sql/storage.go
> +		return ev, fmt.Errorf("open connection error %w", err)
done

2021-01-19 13:24 UTC, Remneva commented on hw12_13_14_15_calendar/internal/server/http/server.go
> +		return fmt.Errorf("shutdown error: %w", err)
done

2021-01-19 13:38 UTC, Remneva commented on hw12_13_14_15_calendar/cmd/calendar/main.go
> +		application = app.NewStoreApp(logg, storage, config)
теперь *App принимает базовый интерфейс, не уверена, что это все решает, но как будто бы логично

2021-01-20 16:34 UTC, balabanovds commented on hw12_13_14_15_calendar/cmd/calendar/main.go
>  	if !config.Mode.MemMode {
а если config.Mode.MemMode то мы передаем в app.New нулевой struct?
Потом в конструкторе app.New Вы делаете провеку опять.. зачем?

2021-01-20 16:34 UTC, balabanovds commented on hw12_13_14_15_calendar/cmd/calendar/main.go
> +		application = app.NewStoreApp(logg, storage, config)
Вы передаете интерфейс BaseStorage в app, а app нужно знать методы Connect, Close?

2021-01-20 16:38 UTC, balabanovds commented on hw12_13_14_15_calendar/cmd/calendar/main.go
> +	storage := new(sql.Storage)
Вы не поняли моего посыла - я хочу передавать в App инстанс стораджа независимо от реализации - будь то SQL, NoSQL, in-memory, Cache...
Главное чтобы этот инстанс реализовал интерфейс. В этом вся прелесть - Вы отвязываетесь от реализации

2021-01-20 16:39 UTC, balabanovds commented on hw12_13_14_15_calendar/internal/app/app.go
> +	if !c.Mode.MemMode {
оно не вынесено, а присутствует и тут и там

2021-01-20 16:40 UTC, balabanovds commented on hw12_13_14_15_calendar/internal/logger/logger.go
> +	cfg := zap.NewProductionConfig()
как сделаете так и будет - можно из конфига прокидывать, можно флагом, можно переменной окружения

2021-01-20 17:44 UTC, balabanovds commented on hw12_13_14_15_calendar/internal/server/http/server.go
> +		if err = json.NewEncoder(resp).Encode(err.Error()); err != nil {
я бы написал три хелпера - отправка серверной ошибки, отправка клиентской ошибки, и отправка тела
Просто у Вас эти куски кода повторяются..

2021-01-20 17:44 UTC, balabanovds commented on hw12_13_14_15_calendar/internal/storage/memory/event.go
> +	defer e.mu.Unlock()
defer вызывайте сразу после Lock.
лучше читается и защит в дальнейшем от лишних вопросов

2021-01-20 17:44 UTC, balabanovds commented on hw12_13_14_15_calendar/cmd/calendar/main.go
> +		application = app.NewMemApp(logg, config)
уже написал, что нужно оперировать на уровне интерфейсов

2021-01-20 17:51 UTC, balabanovds requested changes
Уже лучше! 

Осталиь архитектурные замечания - постарался их описать в комментах. 
Если у Вас возникнут вопросы - без сомнений обращайтесь в Слаке.

Также просьба просмотреть незакрытые комменты по предыдущим проверкам

Успехов!

2021-01-21 09:34 UTC, Remneva commented on hw12_13_14_15_calendar/internal/storage/memory/event.go
> +	defer e.mu.Unlock()
done

2021-01-22 07:11 UTC, Remneva commented on hw12_13_14_15_calendar/internal/server/http/server.go
> +		if err = json.NewEncoder(resp).Encode(err.Error()); err != nil {
у меня получилось два хэлпера

2021-01-22 07:14 UTC, Remneva commented on hw12_13_14_15_calendar/cmd/calendar/main.go
>  	if !config.Mode.MemMode {
done

2021-01-22 07:14 UTC, Remneva commented on hw12_13_14_15_calendar/cmd/calendar/main.go
> +		application = app.NewStoreApp(logg, storage, config)
done

2021-01-22 07:15 UTC, Remneva commented on hw12_13_14_15_calendar/internal/server/http/server.go
> +		return fmt.Errorf("creating a new ServerTransport failed: %w", err)
done

2021-01-22 07:18 UTC, Remneva commented on hw12_13_14_15_calendar/cmd/calendar/main.go
> +	storage := new(sql.Storage)
кажется done

2021-01-22 07:18 UTC, Remneva commented on hw12_13_14_15_calendar/internal/app/app.go
> +	if !c.Mode.MemMode {
done

2021-01-22 10:48 UTC, Remneva commented on hw12_13_14_15_calendar/internal/logger/logger.go
> +	cfg := zap.NewProductionConfig()
done

2021-01-22 10:52 UTC, Remneva commented on hw12_13_14_15_calendar/cmd/calendar/main.go
> +		application = app.NewMemApp(logg, config)
может быть на этот раз done

2021-01-23 20:09 UTC, balabanovds approved these changes
В этот раз нет серьезных замечаний.

10/10

2021-01-23 20:09 UTC, balabanovds commented on hw12_13_14_15_calendar/internal/storage/storage.go
> +	Events() EventsStorage
сейчас в этом нет неообходимости, Вы же даже не вызываете этот метод
в остальном все ок - Вы прокидываете в App EventStorage

2021-01-24 08:42 UTC, merged