Hw11 telnet client
Remneva/otus_hw pull request #13
Opened 2021-01-06 19:29 UTC by Remneva

## Домашнее задание №11 «Клиент TELNET»
### Критерии оценки

- [ ] - Пайплайн зелёный - 4 балла
- [ ] - Добавлены юнит-тесты - до 2 баллов
- [ ] - Понятность и чистота кода - до 4 баллов

2021-01-07 13:04 UTC, balabanovds requested changes
Спасибо за работу.

Много вопросов, давайте мы их порешаем:
- напутали с флагами
- с аргументами вопрос
- непонятно применение контекста
- нет общего состояния соединения, горутина Send не знает завершился ли Receive, и наоборот

2021-01-07 13:04 UTC, balabanovds commented on hw11_telnet_client/main.go
> +	flag.Duration("timeout", 10, "connection timeout")
данная функция возвращает *time.Duration

2021-01-07 13:04 UTC, balabanovds commented on hw11_telnet_client/main.go
> +	flag.StringVar(&port, "port", "4242", "port")
эти флаги host, port не нужны - Вы передаете эти параметры аргументами

2021-01-07 13:04 UTC, balabanovds commented on hw11_telnet_client/main.go
> +	host := os.Args[2]
здесь Вы словите панику если не укажите флаг `-timeout`

2021-01-07 13:04 UTC, balabanovds commented on hw11_telnet_client/main.go
> +	timeoutDuration = timeout * time.Second
timeout всегда равен 0s

2021-01-07 13:04 UTC, balabanovds commented on hw11_telnet_client/main.go
> +	in := os.Stdin
in, out можно не объявлять, а сразу передавать в конструктор

2021-01-07 13:04 UTC, balabanovds commented on hw11_telnet_client/main.go
> +	wg.Wait()
Вы запускаете две горутины. Если одна горутина завершилась, то другая об этом не узнает.
Вы будете тут висеть.

2021-01-07 13:04 UTC, balabanovds commented on hw11_telnet_client/telnet.go
> +		case <-t.ctx.Done():
Вы создали в конструкторе бекграундный контекст. Вы никогда не поймаете Done(), потому что контекст никогда не закончится.

2021-01-07 13:04 UTC, balabanovds commented on hw11_telnet_client/telnet.go
> +	listener net.Listener
а зачем тут listener? мы же вроде клиента делаем?

2021-01-07 13:04 UTC, balabanovds commented on hw11_telnet_client/telnet.go
> +	ctx := context.Background()
контекст лучше прокидывать снаружи из основной горутины. 
но в данной задаче можно обойтись вообще без контекста.

2021-01-13 14:33 UTC, balabanovds requested changes
дописал замечания - пропустил в первый раз

2021-01-13 14:33 UTC, balabanovds commented on hw11_telnet_client/main.go
> +			log.Fatalf("Cannot start receiving goroutine: %v", err.Error())
log.Fatal жестко завершает приложение
это плохая практика желать это в дочерних горутинах

2021-01-13 14:33 UTC, balabanovds commented on hw11_telnet_client/main.go
> +		defer client.Close()
вы закрываете клиента в двух местах - в итоге словите панику

2021-01-31 14:13 UTC, Remneva commented on hw11_telnet_client/main.go
> +	in := os.Stdin
done

2021-01-31 14:15 UTC, Remneva commented on hw11_telnet_client/telnet.go
> +	listener net.Listener
done

2021-01-31 14:15 UTC, Remneva commented on hw11_telnet_client/telnet.go
> +	ctx := context.Background()
done

2021-01-31 14:16 UTC, Remneva commented on hw11_telnet_client/main.go
> +			log.Fatalf("Cannot start receiving goroutine: %v", err.Error())
done

2021-01-31 14:22 UTC, Remneva commented on hw11_telnet_client/telnet.go
> +		case <-t.ctx.Done():
done

2021-01-31 14:24 UTC, Remneva commented on hw11_telnet_client/main.go
> +	timeoutDuration = timeout * time.Second
done

2021-01-31 14:25 UTC, Remneva commented on hw11_telnet_client/main.go
> +	flag.StringVar(&port, "port", "4242", "port")
done

2021-01-31 14:25 UTC, Remneva commented on hw11_telnet_client/main.go
> +	host := os.Args[2]
done

2021-02-02 07:31 UTC, Remneva commented on hw11_telnet_client/main.go
> +	flag.Duration("timeout", 10, "connection timeout")
done

2021-02-02 07:31 UTC, Remneva commented on hw11_telnet_client/main.go
> +	wg.Wait()
done

2021-02-02 07:31 UTC, Remneva commented on hw11_telnet_client/main.go
> +		defer client.Close()
done

2021-02-04 21:24 UTC, balabanovds requested changes
уже лучше, но есть критические замечания

возвращаю на доработку

2021-02-04 21:24 UTC, balabanovds commented on hw11_telnet_client/main.go
> +	flag.Duration("timeout", 10, "connection timeout")
ничего не изменилось. переменная timeout всегда будет равна 0s

2021-02-04 21:24 UTC, balabanovds commented on hw11_telnet_client/main.go
> +	if len(os.Args) == 3 {
если я ввел некорректное число аргументов я хочу видеть дружественный help, но сейчас я вижу
```
panic: runtime error: index out of range [2] with length 2

goroutine 1 [running]:
main.main()
        /hw11_telnet_client/main.go:31 +0x89b
exit status 2
```

2021-02-04 21:24 UTC, balabanovds commented on hw11_telnet_client/main.go
> +	if len(os.Args) == 3 {
есть решение в две строчки -  посмотрите в сторону пакета flag

2021-02-04 21:24 UTC, balabanovds commented on hw11_telnet_client/main.go
> +		break
почему? что сделает break?

2021-02-04 21:24 UTC, balabanovds commented on hw11_telnet_client/main.go
> +	err = client.Close()
Close лучше перенести ближе к Connect и вынести в defer

2021-02-04 21:24 UTC, balabanovds commented on hw11_telnet_client/telnet.go
> +	if err := t.conn.Close(); err != nil {
зачем обрабатывать тут ошибку - Вы же ее обрабатываете в main!

2021-02-04 21:24 UTC, balabanovds commented on hw11_telnet_client/telnet_test.go
> +	t.Run("close connection error", func(t *testing.T) {
у Вас тесты одинаково называются

2021-02-05 14:49 UTC, Remneva commented on hw11_telnet_client/main.go
> +	flag.Duration("timeout", 10, "connection timeout")
простити, не дошло

2021-02-05 14:50 UTC, Remneva commented on hw11_telnet_client/main.go
> +	if len(os.Args) == 3 {
если правильно поняла, done

2021-02-05 14:50 UTC, Remneva commented on hw11_telnet_client/main.go
> +		break
ничего

2021-02-05 14:52 UTC, Remneva commented on hw11_telnet_client/telnet_test.go
> +	t.Run("close connection error", func(t *testing.T) {
они полостью одинаковые, удалила

2021-02-05 15:31 UTC, Remneva commented on hw11_telnet_client/main.go
> +	err = client.Close()
done

2021-02-07 06:06 UTC, balabanovds submitted a review, later dismissed
Хорошо.
9/10

2021-02-07 06:06 UTC, balabanovds commented on hw11_telnet_client/main.go
> +	if len(os.Args) == 4 {
Есть flag.NArgs

2021-02-07 06:06 UTC, balabanovds commented on hw11_telnet_client/main.go
> +		flag.PrintDefaults()
flag.Usage()

2021-02-07 11:38 UTC, Remneva commented on hw11_telnet_client/main.go
> +	if len(os.Args) == 4 {
done

2021-02-07 11:39 UTC, Remneva commented on hw11_telnet_client/main.go
> +		flag.PrintDefaults()
done

2021-02-24 05:19 UTC, merged