Hw03 frequency analysis
Remneva/otus_hw pull request #2
Opened 2020-09-20 15:08 UTC by Remneva

## Домашнее задание №3 «Частотный анализ»

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2020-09-20 16:37 UTC, kulti requested changes
Неплохое решение, работает верно. Глядя на код, создается ощущение, что еще остались некоторые непонятные моменты в работе со слайсами. Предлагаю обсудить и доразобраться.

Если что, можете писать мне в слак в личку любые вопросы и непонятные моменты. Я объясню и подскажу, в каком направлении искать решение.

2020-09-20 16:37 UTC, kulti commented on hw03_frequency_analysis/top.go
> +	slice := make([]kv, len(cache))
`len(cache)` тут будт 0, т.к. `cache` создается строчкой выше без элементов. Думаю, тут была заложена какая-то идея. Если никакой идеи не было, то можно просто `var slice []kv` или `slice := []kv{}`.

2020-09-20 16:37 UTC, kulti commented on hw03_frequency_analysis/top.go
> +	slice2 := make([]kv, 10)
А зачем нужен `slice2`?

2020-09-20 16:37 UTC, kulti commented on hw03_frequency_analysis/top.go
> +		if i < 10 {
Тут получается, что обходится весь `slice`, но элементы после десятого игнорируются. Это не имеет смысла. Предлагаю переделать цикл так, чтобы обходить только 10 элементов.

2020-09-20 16:37 UTC, kulti commented on hw03_frequency_analysis/top_test.go
>  	})
Попробуйте добавить еще один тест. Например, можно подумать о граничных условиях. Функция должна выдавать top 10, а что, если разных слов будет меньше? Или, что будет, если все слова разные?

2020-09-21 14:23 UTC, Remneva commented on hw03_frequency_analysis/top.go
> +	slice := make([]kv, len(cache))
изначально был вариант  `var slice []kv` , что не понравилось линтеру: `Consider preallocating `slice` (prealloc)` , где-то на stack overflow попался такой вариант решения =/

2020-09-21 14:47 UTC, Remneva commented on hw03_frequency_analysis/top.go
> +	slice2 := make([]kv, 10)
Свежим взглядом после ваших комментариев, честно говоря, вижу только лишний объект не имеющий смысла)

2020-09-23 11:55 UTC, Remneva commented on hw03_frequency_analysis/top.go
> +		if i < 10 {
возможно есть более красивый способ остановить цикл после  N-го элемента, но теперь вроде лишних обоходов не делает

2020-09-23 11:55 UTC, Remneva commented on hw03_frequency_analysis/top_test.go
>  	})
Тесты добавлены

2020-09-23 16:46 UTC, kulti approved these changes
Теперь работа со слайсами намного лучше. Цикл формирования result все еще немного "дикий". Написал, в каком направлении можно подумать, чтобы улучшить, если хочется 10 баллов.

ДЗ принято - 9/10.

2020-09-23 16:46 UTC, kulti commented on hw03_frequency_analysis/top.go
> +		if i < 10 {
Да, теперь лишних итераций цикла нет.

В текущем варианте проблема в том, что под result выделяется столько памяти, сколько элементов есть в slice, хотя по факту больше 10 не нужно. Как вариант, можно перед циклом выбрать финальную длину для result и это число пригодится и для make и для условия выхода из цикла.

2021-02-24 05:19 UTC, merged