Hw06 pipeline execution
Remneva/otus_hw pull request #9
Opened 2020-11-22 17:28 UTC by Remneva

## Домашнее задание №6 «Пайплайн»
Необходимо реализовать функцию для запуска конкуррентного пайплайна, состоящего из стейджей.

### Критерии оценки

- [ ] - CI-пайплайн зелёный - 5 баллов
- [ ] - Добавлены новые юнит-тесты - до 2 баллов
- [ ] - Понятность и чистота кода - до 3 баллов

#### Зачёт от 7 баллов

2020-11-23 18:57 UTC, kulti requested changes
Хорошее решение. Есть пара ошибок. Предлагаю поправить.

2020-11-23 18:57 UTC, kulti commented on hw06_pipeline_execution/pipeline.go
> +				}
Как я понимаю из цепочки if-ов, `vv != nil` — это проверка на то закрыт ли канал in. Если так, то это некорректно. В канал вполне можно записать zero-value значение. Правильно сделать так:
```
case vv, ok := <-in:
	if !ok {
		return
	}
```

2020-11-23 18:57 UTC, kulti commented on hw06_pipeline_execution/pipeline.go
> +		out = insertDone(s(insertDone(out, done)), done)
Что-то никак не пойму, зачем дважды использовать обертку insertDone. Можете, пояснить?

2020-11-23 18:57 UTC, kulti commented on hw06_pipeline_execution/pipeline.go
> +					out <- vv
Если идет завершение по done, то горутина, читающая из этого out, может завершится раньше. В итоге эта запись может зависнуть навсегда.

2020-11-23 18:57 UTC, kulti commented on hw06_pipeline_execution/pipeline_test.go
> +	t.Run("Concatenation string", func(t *testing.T) {
Хорошая идея проверить работу на другом наборе данных 👍

2020-11-24 15:38 UTC, Remneva commented on hw06_pipeline_execution/pipeline.go
> +		out = insertDone(s(insertDone(out, done)), done)
ой это я просто забыла убрать, добавляла, пока не поняла где надо ловить входящий nil из потока in. Это лишнее здесь, уберу.

2020-11-28 10:19 UTC, kulti requested changes
Здорово, что поправили замечания. Правда, одно осталось :) Предлагаю его тоже поправить. Если нет идей, что с ним делать, то всегда можно написать мне в слаке, я подскажу.

2020-12-03 06:40 UTC, kulti approved these changes
Теперь все супер. ДЗ принято — 10/10.

2020-12-03 14:35 UTC, merged